services:
  ai-assistant:
    image: ai-assistant:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7075:7075"
    volumes:
      - /data/ai_assistant
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NS_API_KEY=${NS_API_KEY}
volumes:
  ai_assistant: