name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        java-version: 21
        java-distribution: temurin
        maven-version: 3.9.9
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests and generate JaCoCo report
      run: mvn test jacoco:report
    - name: Check code style with Google Java Format
      run: mvn com.spotify.fmt:fmt-maven-plugin:check
#    - name: Check for vulnerabilities with OWASP Dependency-Check
#      run: mvn verify org.owasp:dependency-check-maven:check
    - name: Display Dependency Updates
      run: mvn versions:display-dependency-updates
    - name: Display Plugin Updates
      run: mvn versions:display-plugin-updates